#! /bin/sh
# keep csci[36]]50 port scan server running
while [ true ]; do
   date >> ports.log
   java -cp ".:bson-5.1.0.jar:mongodb-driver-core-5.1.0.jar:mongodb-driver-sync-5.1.0.jar:slf4j-simple-2.0.12.jar:slf4j-api-2.0.12.jar" PortServer >> ports.log
   sleep 120
done
