name: port_scan_log
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^1.1.0
  mysql1: ^0.19.0
  intl: ^0.17.0


dev_dependencies:
  pedantic: ^1.9.0
